# Generated by Django 4.2.5 on 2023-09-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=25)),
                ('product_description', models.CharField(max_length=100)),
                ('product_price', models.PositiveIntegerField()),
                ('product_discount', models.PositiveIntegerField()),
                ('product_slug', models.CharField(max_length=200)),
                ('product_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
